name: Nightly & Manual NetPass Build

on:
  schedule:
    - cron: '0 3 * * *'  # every day at 3:00 AM UTC
  workflow_dispatch:      # allows manual trigger from GitHub UI

jobs:
  build:
    name: Build NetPass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (for logs)
        uses: actions/checkout@v4

      - name: Clone GitLab netpass main branch with submodules
        run: |
          git clone --depth 1 --recurse-submodules https://gitlab.com/3ds-netpass/netpass.git
          cd netpass
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Create output directory
        run: mkdir -p output

      - name: Build using Docker
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}/netpass:/build/source \
            -v ${{ github.workspace }}/output:/output \
            ghcr.io/introkun/netpass-builder:latest

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: netpass-${{ env.GIT_HASH }}
          path: |
            output/*.3dsx
            output/*.cia

      - name: Install qrencode
        run: sudo apt-get install -y qrencode
      
      - name: Generate QR code for .cia download
        run: |
          URL="https://github.com/${{ github.repository }}/releases/download/nightly-${{ env.GIT_HASH }}/netpass.cia"
          qrencode -o netpass.cia-qr.png "$URL"
      
      - name: Commit QR code to repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git pull
          mkdir -p qr
          cp netpass.cia-qr.png qr/${{ env.GIT_HASH }}.png
          git add qr/${{ env.GIT_HASH }}.png
          git commit -m "Add QR for nightly-${{ env.GIT_HASH }}"
          git push

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ env.GIT_HASH }}
          name: Nightly Build ${{ env.GIT_HASH }}
          body: |
            📱 **Scan to install netpass.cia on 3DS**

            ![QR](https://github.com/${{ github.repository }}/raw/main/qr/${{ env.GIT_HASH }}.png)

          files: |
            output/*.3dsx
            output/*.cia
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
